version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: dev
    volumes:
       - ./:/code
    working_dir: /code
    command: ["sh", "-c", "mvn install -DskipTests && mvn spring-boot:run -pl application-spring"]
    tty: true
    environment:
      SERVER_PORT: ${SERVER_PORT}
      ALPINEBITS_PATH: ${ALPINEBITS_PATH}
      ODH_URL: ${ODH_URL}
      ODH_AUTH_URL: ${ODH_AUTH_URL}
      ODH_AUTH_CLIENT_ID: ${ODH_AUTH_CLIENT_ID}
      ODH_AUTH_CLIENT_SECRET: ${ODH_AUTH_CLIENT_SECRET}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
